/**
 * The real templates, as the API really returns them, through this renderer.
 *
 * Every other test here feeds the renderer a fixture written to exercise one
 * rule. This one reads payloads produced by the platform's own transform from
 * the templates an author actually starts from, so it asks the question that
 * matters: would a person see this message.
 *
 * The payloads are generated by the platform repo's
 * tests/message-pipeline-simulation.test.ts with TOLINKU_SIM_DIR set. When
 * they are absent the file falls back to an inline copy of one, so this still
 * runs anywhere, and says which mode it used.
 */

jest.mock('react-native', () => ({
  Text: 'Text',
  View: 'View',
  Image: 'Image',
  TouchableOpacity: 'TouchableOpacity',
  ImageBackground: 'ImageBackground',
  Linking: { openURL: jest.fn(() => Promise.resolve()) },
}));

import fs from 'fs';
import path from 'path';
import { PuckComponentRenderer, drawsAnything, type RenderOptions } from '../src/messages/components';
import type { MessageAppContext, MessageComponent } from '../src/types';

const SIM_FILE = process.env.TOLINKU_SIM_DIR
  ? path.join(process.env.TOLINKU_SIM_DIR, 'message-payloads.json')
  : '';

const FALLBACK_APP: MessageAppContext = {
  name: 'Example',
  icon_url: 'https://cdn.example.com/icon.png',
  ios_store_url: 'https://apps.apple.com/app/id1',
  android_store_url: 'https://play.google.com/store/apps/details?id=x',
  deep_link_url: 'https://links.example.com/install',
  ios_badge_url: 'https://links.example.com/images/defaults/badges/ios-store-badge-black.png',
  android_badge_url: 'https://links.example.com/images/defaults/badges/play-store-badge-black.png',
};

/** One representative payload, for when the generated ones are not present. */
const FALLBACK_PAYLOADS = [
  {
    id: 'inline-announcement',
    app: FALLBACK_APP,
    content: {
      root: { props: { bgColor: '#ffffff', padding: 20, contentWidth: 480 } },
      content: [
        { type: 'Spacer', props: { id: 's1', height: 8 } },
        { type: 'Image', props: { id: 'i1', url: 'https://links.example.com/images/defaults/icons/bell.png', width: '44px', borderRadius: 0 } },
        { type: 'Heading', props: { id: 'h1', text: 'Something new', fontSize: 24, alignment: 'center' } },
        { type: 'TextBlock', props: { id: 't1', content: 'Read the [notes](https://example.com/notes).', alignment: 'center' } },
        { type: 'Button', props: { id: 'b1', label: 'Open', action: 'myapp://order/4821', style: 'soft', bgColor: '#1B1B1B', borderRadius: 0 } },
      ],
    },
  },
];

const payloads: any[] =
  SIM_FILE && fs.existsSync(SIM_FILE)
    ? JSON.parse(fs.readFileSync(SIM_FILE, 'utf8'))
    : FALLBACK_PAYLOADS;

const usingGenerated = !!(SIM_FILE && fs.existsSync(SIM_FILE));

const render = (component: MessageComponent, options: Partial<RenderOptions>) =>
  PuckComponentRenderer({ component, messageId: 'sim', options: options as RenderOptions }) as any;

/** Every element in a returned tree. */
const flatten = (node: any, out: any[] = []): any[] => {
  if (!node) return out;
  if (Array.isArray(node)) {
    node.forEach(n => flatten(n, out));
    return out;
  }
  if (typeof node !== 'object') return out;
  out.push(node);
  flatten(node.props?.children, out);
  return out;
};

describe(`stock message templates on this renderer (${usingGenerated ? 'generated payloads' : 'inline fallback'})`, () => {
  it('has payloads to render', () => {
    expect(payloads.length).toBeGreaterThan(0);
  });

  for (const payload of payloads) {
    describe(payload.id, () => {
      const options = { app: payload.app, zones: payload.content.zones, onButtonPress: jest.fn() };

      it('would draw something, so the message is not an empty card', () => {
        expect(drawsAnything(payload.content.content, payload.app)).toBe(true);
      });

      it('draws every component it was given', () => {
        for (const component of payload.content.content) {
          const el = render(component, options);
          // A null here is a component that renders as a gap on the device
          // while the dashboard preview shows it.
          expect({ type: component.type, drew: el !== null }).toEqual({ type: component.type, drew: true });
        }
      });

      it('gives every image a source and a size React Native can lay out', () => {
        for (const component of payload.content.content) {
          if (component.type !== 'Image') continue;
          const el = render(component, options);
          expect(el.props.uri).toMatch(/^https?:\/\//);
          // The constraint that belongs here more than anywhere else: React
          // Native decodes no SVG on either platform, so an SVG reaching this
          // renderer is a blank space, which is the bug the rewrite exists
          // for. An earlier version of this file checked only that the URL was
          // absolute, and a deliberate revert of that rewrite sailed past it.
          expect(el.props.uri.toLowerCase()).not.toMatch(/\.svg($|\?)/);
          // Width is either a number or a percentage; height may be undefined,
          // which means measure it, never an unusable string.
          const { width, height } = el.props;
          expect(typeof width === 'number' || /^\d+(\.\d+)?%$/.test(String(width))).toBe(true);
          if (height !== undefined) expect(typeof height).toBe('number');
        }
      });

      it('gives every button a label and something to do', () => {
        for (const component of payload.content.content) {
          if (component.type !== 'Button') continue;
          const el = render(component, options);
          const label = flatten(el).find(n => n.type === 'Text');
          expect(String(label.props.children).trim().length).toBeGreaterThan(0);
          expect(el.props.style.backgroundColor).toBeTruthy();
        }
      });
    });
  }
});

describe('a section, which the stock templates do not use', () => {
  // The bug that started this was a Section drawing an empty box, so it is
  // worth exercising even though no template ships one.
  const app = payloads[0]?.app || FALLBACK_APP;
  const content = {
    root: { props: {} },
    content: [{ type: 'Section', props: { id: 'sec1', bgColor: '#f5f5f5', padding: 0 } }],
    zones: {
      'sec1:content': [
        { type: 'Heading', props: { id: 'h', text: 'Inside the section' } },
        { type: 'Button', props: { id: 'b', label: 'Go', action: 'myapp://inside' } },
      ],
    },
  };

  it('hands its children to the renderer instead of drawing an empty box', () => {
    const el = render(content.content[0] as any, { app, zones: content.zones });
    const children = el.props.children as any[];
    expect(children).toHaveLength(2);
    expect(children.map(c => c.props.component.type)).toEqual(['Heading', 'Button']);
    expect(el.props.style.padding).toBe(0);
  });

  it('counts as drawing something', () => {
    expect(drawsAnything(content.content as any, app)).toBe(true);
  });
});
